# -*- coding: utf-8 -*-
"""rnn stock price multiple constraint

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DBFSVgHKHfTZ4WeXxQcr4UNVzDZBKYWR

# Recurrent Neural Network
"""

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd



"""### Importing the training set"""

dataset_train=pd.read_csv('Google_Stock_Price_Train.csv')
my_train=dataset_train.iloc[:,1:]  #creating a numarray that contains the open price of the stock
training_set=my_train.replace(",","",regex=True)

print(training_set)
# print(training_set[0:1,4:5])
# training_set[0:1,4:5]=training_set[0:1,4:5].replace(",","")
# print(training_set[0:1,4:5])

"""### Feature Scaling"""

from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))  #all stock prices will be between 0 and 1
training_set_scaled=sc.fit_transform(training_set)
print(training_set_scaled)

"""### Creating a data structure with 60 timesteps and 1 output

Timesteps:Data structure specifying what the rnn needs to remeber.
"""

X_train=[]
y_train=[]
for i in range(60,1258): #we will select the first 60 values to predict the first value and so on
  X_train.append(training_set_scaled[i-60:i])  #will put first 60 value in x
  y_train.append(training_set_scaled[i,0])#will put the value we will predict
X_train,y_train=np.array(X_train),np.array(y_train)

#improvement added
# X_train_last_column = X_train[:,-1]
# X_train_min = X_train.min(axis=1)
# X_train_max = X_train.max(axis=1)
# X_diff = X_train_max-X_train_min
# X_train_divided = (X_train-X_train_min[:, np.newaxis] )/X_diff[:, np.newaxis]
# y_train_divided = (y_train-X_train_min )/X_diff

"""## Part 2 - Building and Training the RNN

### Importing the Keras libraries and packages
"""

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

"""### Initialising the RNN"""

regressor=Sequential()

"""### Adding the first LSTM layer and some Dropout regularisation"""

regressor.add(LSTM(units = 50, return_sequences = True, input_shape = (X_train.shape[1],5)))
regressor.add(Dropout(0.2))

"""Dropout momentarily (in a batch of input data) switches off some neurons in a layer so that they do not contribute any information or learn any information during those updates, and the onus falls on other active neurons to learn harder and reduce the error.

### Adding a second LSTM layer and some Dropout regularisation
"""

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

"""### Adding a third LSTM layer and some Dropout regularisation"""

regressor.add(LSTM(units = 50, return_sequences = True))
regressor.add(Dropout(0.2))

"""### Adding a fourth LSTM layer and some Dropout regularisation"""

regressor.add(LSTM(units = 50, return_sequences = False)) #false as it the last lstm layer
regressor.add(Dropout(0.2))

"""### Adding the output layer"""

regressor.add(Dense(units=1))

"""### Compiling the RNN"""

regressor.compile(optimizer='adam' ,loss='mean_squared_error')

"""### Fitting the RNN to the Training set"""

regressor.fit(X_train,y_train,epochs=100,batch_size=32)

"""## Part 3 - Making the predictions and visualising the results

### Getting the real stock price of 2017
"""

dataset_test = pd.read_csv('Google_Stock_Price_Test.csv')
real_stock_price = dataset_test.iloc[:,1:2].values

"""### Getting the predicted stock price of 2017"""

data_set1=dataset_train.iloc[:,1:]
data_set2=dataset_test.iloc[:,1:]
dataset_total = pd.concat((data_set1, data_set2), axis = 0)
dataset_total=dataset_total.replace(",","",regex=True)
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 60:].values
# inputs = inputs.reshape(-1,1)
# inputs=inputs.replace(",","",regex=True)
inputs = sc.transform(inputs)
# print(inputs)
# inputs=dataset_test.iloc[:-1,1:]
# 
# inputs=np.asarray(inputs).astype(np.float32)
# inputs=sc.transform(inputs)
X_test = []
for i in range(60, 80):
    X_test.append(inputs[i-60:i])
X_test = np.array(X_test)
# # X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = regressor.predict(X_test)
# predicted_stock_price = sc.inverse_transform(predicted_stock_price)
predicted_stock_price=predicted_stock_price*(1/1.86025746e-03)
predicted_stock_price=predicted_stock_price+300



"""### Visualising the results"""

plt.plot(real_stock_price, color = 'red', label = 'Real Google Stock Price')
plt.plot(predicted_stock_price, color = 'blue', label = 'Predicted Google Stock Price')

plt.title('Google Stock Price Prediction')
plt.xlabel('Time')
plt.ylabel('Google Stock Price')
plt.legend()
plt.show()

plt.plot(abs(real_stock_price- predicted_stock_price), color = 'red', label = 'Difference')
plt.xlabel('Time')
plt.ylabel('difference')
plt.legend()
plt.show()

regressor.save('rnn_new.h5')